name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write # important: allows pushing to the repo

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Rohamidi
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
